### ISSUE TITLE
Question about size

### ISSUE THREAD

**Issue by paldepind** [danr/ts-quickcheck#4]
I'm having a tiny bit of trouble understanding the purpose of the `size` property in `GenEnv`. From what I can [see here](https://github.com/danr/ts-quickcheck/blob/027119a8563b372af2d0dbb3283769f34774e3f5/src/main.ts#L242) tests are run the size given to the generator is in the range between 0 and 99. Jack seems to be doing [the same thing](https://github.com/jystic/purescript-jack/blob/de59bef08ee7deb919085484e2a65a951be8c6ef/src/Jack/Property.purs#L125). Why does the size have to vary like that? Why not give "full" size every time?

`size` [affects nat](https://github.com/danr/ts-quickcheck/blob/027119a8563b372af2d0dbb3283769f34774e3f5/src/Gen.ts#L228) which in turn means that it ends up affecting the other number generators and `array`. But, if I do something like this:

```js
QC.forall(Gen.nat, (n) => expr);
```

Then, by default, `expr` will be run 100 times. But `n` will never get larger than 100. In the first run `n` will be a number between 0 and 1, in the next between 0 and 2, then 0 and 3, and so on. Only in the final run with size 99 is there a 1% change that `n` will be 100. This doesn't seem optimal. The numbers will be distributed towards the lower end and `expr` will be run many times with the same input.

**Comment by danr** [comment]
It is not necessary to use a size parameter but it is standard practice in implementations. It looks a bit weird when only generating one nat, but already when generating two  numbers, (using `Gen.nat.replicate(2)` or `Gen.record({x: Gen.nat, y: Gen.nat})`) the number of inputs that are exactly the same are very few.

The reason why we don't want to try with the full size immediately is twofold.
1. If the time complexity of the expression is dependent of the input size we want to  try to find a counterexample as quickly as possible.
2. The initial search space for shrinking should be as small as possible so starting from a small value helps a lot.

**Comment by paldepind** [comment]
Thanks for the explanation. It makes sense. Especially in the cases where the size is used to construct a larger structure like in `array`.

But I still think it's a problem that `Gen.int` will only result in numbers between -100 and 100. That is a very small range. [`boundedInt`](https://github.com/jystic/purescript-jack/blob/master/src/Jack/Combinators.purs#L102) in Jack returns numbers in the entire integer range as far as I can tell. What about making `Gen.nat` independent of the size like in Jack? That seems like a better default to me.

**Comment by danr** [comment]
I agree that it makes sense to provide generators for the entire range. 

I this these are the most important number ranges:

    [0, size]
    [1, size]
    [-size, size]

    [0, maxBound]
    [1, maxBound]
    [-maxBound, maxBound]

Here `size` is the 0-100 bound and with `maxBound` I mean the largest integer that fits without becoming a float in JS.

These are the names I'm using right now:

    nat [0, size]
    pos [1, size]
    int [-size, size]

    ?   [0, maxBound]
    ?   [1, maxBound]
    ?   [-maxBound, maxBound]
    
This is another reasonable naming scheme in my opinion:

    nat [0, size]
    ?   [1, size]
    ?   [-size, size]

    uint [0, maxBound]
    ?    [1, maxBound]
    int  [-maxBound, maxBound]
    
But I'm not sure how to complete it in an elegant way.

**Comment by paldepind** [comment]
> I this these are the most important number ranges:

I agree. That looks right.

Here are two ideas.

1. Those in the _largest_ range get a _longer_ name.
```
nat [0, size]
pos [1, size]
int [-size, size]

natural   [0, maxBound]
positive  [1, maxBound]
integer   [-maxBound, maxBound]
```

2. Those that depends on the size are prefixed with `sized` which makes it explicit that they depend on sized and that they can be manipulated with `big`, `huge`, `pow`, etc.

```
sizedNat [0, size]
sizedPos [1, size]
sizedInt [-size, size]

nat   [0, maxBound]
pos   [1, maxBound]
int   [-maxBound, maxBound]
```

**Comment by danr** [comment]
I like the name pairs `int` - `integer` etc, but I'm starting to wonder what we should use such big numbers for.

If the generator can return [`Number.MAX_SAFE_INTEGER`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) then one cannot safely add or multiply it.

Some other smaller upper bound could be used, like what fits in a signed 32 bit precision integer. Then at least it can be added to and multiplied with small constants. What do you think about that?

**Comment by danr** [comment]
One good excuse to be within the i32 boundaries is that the bit operations in JS all operate on that range.

**Comment by danr** [comment]
They are added now, generating 32-bit integers.

**Comment by paldepind** [comment]
Good point.

32 bit integers are actually also what I was interested in.
